E-Farm/E-Farm/Areas/Admin/Models/AccountAdmin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace E_Farm.Areas.Admin.Models
{
    [Table("AccountAdmin")]
    public class AccountAdmin
    {
        [Key]
        [Display(Name = "Mã admin")]
        [StringLength(36)]
        public string AccAdminId { get; set; }
        
        [Display(Name = "Họ và tên")]
        [StringLength(126)]
        [Required(ErrorMessage = "Mời nhập tên")]
        [RegularExpression("[A-Za-z ]*", ErrorMessage = "Tên không hợp lệ")]
        public string Fullname { get; set; }

        [Display(Name = "Tên đăng nhập")]
        [StringLength(maximumLength: 26, MinimumLength = 8, ErrorMessage = "Tên đăng nhập phải từ 8 đến 26 ký tự")]
        [Required(ErrorMessage = "Mời nhập tên đăng nhập")]
        public string Username { get; set; }

        [Display(Name = "Mật khẩu")]
        [RegularExpression("^[a-zA-Z0-9]*$", ErrorMessage = "Mật khẩu chỉ chứa số và chữ")]
        [StringLength(maximumLength:36, MinimumLength = 8, ErrorMessage = "Mật khẩu phải từ 8 đến 26 ký tự")]
        [Required(ErrorMessage = "Mời nhập mật khẩu")]
        public string Password { get; set; }

        [Display(Name = "Ảnh")]
        [StringLength(200)]
        public string Picture { get; set; }

        [Display(Name = "Ngày tạo")]
        public DateTime CreateDate { get; set; }
    }
}

E-Farm/E-Farm/Areas/Admin/Controllers/AccountAdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E_Farm.Areas.Admin.Models;

namespace E_Farm.Areas.Admin.Controllers
{
    public class AccountAdminsController : Controller
    {
        private DataEntities db = new DataEntities();
        
        public ActionResult Index()
        {
            return View(db.AccountAdmins.ToList());
        }
        
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccountAdmin accountAdmin = db.AccountAdmins.Find(id);
            if (accountAdmin == null)
            {
                return HttpNotFound();
            }
            return View(accountAdmin);
        }
        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string username, AccountAdmin accountAdmin, HttpPostedFileBase UploadAvtAdmin)
        {

            var check = db.AccountAdmins.SingleOrDefault(x => x.Username == accountAdmin.Username);
            if (check != null)
            {
                TempData["errMessage"] = "<div class='alert alert-danger'><strong>Cảnh báo! </strong>Tên đăng nhập đã tồn tại.</div>";
                return View(accountAdmin);
            }

            if (ModelState.IsValid)
            {
                if (UploadAvtAdmin != null)
                {
                    UploadAvtAdmin.SaveAs(Server.MapPath("~/Areas/Admin/Content/imgAccAdmin/") + UploadAvtAdmin.FileName);
                    accountAdmin.Picture = "/Areas/Admin/Content/imgAccAdmin/" + UploadAvtAdmin.FileName;
                }

                Guid guid = Guid.NewGuid();
                accountAdmin.AccAdminId = guid.ToString();
                accountAdmin.CreateDate = @DateTime.Now;
                accountAdmin.Password = accountAdmin.Password.ToMD5();
                db.AccountAdmins.Add(accountAdmin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(accountAdmin);
        }
        
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AccountAdmin accountAdmin = db.AccountAdmins.Find(id);
            if (accountAdmin == null)
            {
                return HttpNotFound();
            }
            return View(accountAdmin);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AccountAdmin accountAdmin, HttpPostedFileBase UploadAvtAdmin)
        {

            if (ModelState.IsValid)
            {
                if (UploadAvtAdmin != null)
                {
                    UploadAvtAdmin.SaveAs(Server.MapPath("~/Areas/Admin/Content/imgAccAdmin/") + UploadAvtAdmin.FileName);
                    accountAdmin.Picture = "/Areas/Admin/Content/imgAccAdmin/" + UploadAvtAdmin.FileName;
                }
                accountAdmin.Password = accountAdmin.Password.ToMD5();
                db.Entry(accountAdmin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(accountAdmin);
        }
        
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccountAdmin accountAdmin = db.AccountAdmins.Find(id);
            if (accountAdmin == null)
            {
                return HttpNotFound();
            }
            db.AccountAdmins.Remove(accountAdmin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
    }
}

E-Farm/E-Farm/Areas/Admin/Views/AccountAdmins/Create.cshtml
@model E_Farm.Areas.Admin.Models.AccountAdmin

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align:center">Thêm tài khoản</h2>
@Html.Raw(TempData["errMessage"])

@using (Html.BeginForm("Create", "AccountAdmins", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Fullname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fullname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fullname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="UploadAvtAdmin" class="form-control" />
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

E-Farm/E-Farm/Areas/Admin/Views/AccountAdmins/Details.cshtml
@model E_Farm.Areas.Admin.Models.AccountAdmin

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align:center">Thông tin tài khoản</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fullname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fullname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            <img src="@Model.Picture" width="220"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Cập nhật", "Edit", new { id = Model.AccAdminId }) |
    @Html.ActionLink("Quay lại", "Index")
</p>

E-Farm/E-Farm/Areas/Admin/Views/AccountAdmins/Edit.cshtml
@model E_Farm.Areas.Admin.Models.AccountAdmin

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align:center">Cập nhật tài khoản</h2>


@using (Html.BeginForm("Edit", "AccountAdmins", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AccAdminId)

        <div class="form-group">
            @Html.LabelFor(model => model.Fullname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fullname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fullname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                <input type="file" name="UploadAvtAdmin" class="form-control" />
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

E-Farm/E-Farm/Areas/Admin/Views/AccountAdmins/Index.cshtml
@model IEnumerable<E_Farm.Areas.Admin.Models.AccountAdmin>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align:center">Danh sách tài khoản</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Fullname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Fullname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            <img src="@item.Picture" width="130"/>
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AccAdminId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AccAdminId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AccAdminId }, new { @onclick = "return confirm('Bạn có muốn xóa không?')" })
        </td>
    </tr>
}

</table>