E-Farm/E-Farm/Areas/Admin/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Farm.Areas.Admin.Models
{
    [Table("Product")]
    public class Product
    {
        [Key]
        [Display(Name = "Mã sản phẩm")]
        public int ProductId { get; set; }

        [ForeignKey("Category")]
        [Required(ErrorMessage = "Mời chọn danh mục")]
        [Display(Name = "Danh mục")]
        public int CateId { get; set; }

        [Required(ErrorMessage = "Mời nhập tên sản phẩm")]
        [Display(Name = "Tên sản phẩm")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Mời nhập số lượng")]
        [Display(Name = "Số lượng")]
        [Range(0,100000,ErrorMessage = "Lỗi nhập số lượng")]
        public int Quantity { get; set; }

        [Required(ErrorMessage = "Mời nhập giá")]
        [Display(Name = "Giá")]
        [Range(0, 1000000000, ErrorMessage = "Lỗi nhập giá")]
        public float Price { get; set; }

        [Display(Name = "Giá khuyến mại")]
        [Range(0, 1000000000, ErrorMessage = "Lỗi nhập giá khuyến mãi")]
        public float? PriceDiscount { get; set; }

        [Display(Name = "Ảnh")]
        public string Picture { get; set; }

        [Display(Name = "Mô tả")]
        [AllowHtml]
        public string Description { get; set; }
        
        [Display(Name = "Ngày tạo")]
        public DateTime CreateDate { get; set; }

        [Display(Name = "Trạng thái")]
        public bool Status { get; set; }

        public Category Category { get; set; }

        public virtual ICollection<CommentProduct> CommentProducts { get; set; }

        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

E-Farm/E-Farm/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E_Farm.Areas.Admin.Models;
using PagedList;
namespace E_Farm.Areas.Admin.Controllers
{
    public class ProductsController : Controller
    {
        private DataEntities db = new DataEntities();

        public ActionResult Index(string search, int? pageNo)
        {
            if (search == null)
            {
                search = "";
            }
            int pageSize = 5;
            int pageNumber = pageNo ?? 1;
            return View(db.Products.Include(x => x.Category).Where(x => x.Name.Contains(search)).ToList().ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Product product = db.Products.Include(o => o.Category).FirstOrDefault(x => x.ProductId == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        public PartialViewResult Search(string name, int? pageNo)
        {
            int pageSize = 5;
            int pageNumber = pageNo ?? 1;
            var data = db.Products.Include(b => b.Category).Where(x => x.Name.Contains(name)).ToList();
            return PartialView(data.ToPagedList(pageNumber,pageSize));
        }

        public ActionResult Create()
        {
            ViewBag.CateId = new SelectList(db.Categorys, "CateId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product, HttpPostedFileBase UploadImgProducts)
        {
            var checkName = db.Products.SingleOrDefault(x => x.Name == product.Name);
            if (checkName != null)
            {
                TempData["errMessage"] = "<div class='alert alert-danger'><strong>Cảnh báo! </strong>Sản phẩm đã tồn tại trong kho</div>";
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid)
            {
                if (UploadImgProducts != null)
                {
                    UploadImgProducts.SaveAs(Server.MapPath("~/Areas/Admin/Content/imagesProducts/") + UploadImgProducts.FileName);
                    product.Picture = "/Areas/Admin/Content/imagesProducts/" + UploadImgProducts.FileName;
                }
                product.CreateDate = DateTime.Now;
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CateId = new SelectList(db.Categorys, "CateId", "Name", product.CateId);
            return View(product);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CateId = new SelectList(db.Categorys, "CateId", "Name", product.CateId);
            return View(product);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product, HttpPostedFileBase UploadImgProducts)
        {
            if (ModelState.IsValid)
            {
                if (UploadImgProducts != null)
                {
                    UploadImgProducts.SaveAs(Server.MapPath("~/Areas/Admin/Content/imagesProducts/") + UploadImgProducts.FileName);
                    product.Picture = "/Areas/Admin/Content/imagesProducts/" + UploadImgProducts.FileName;
                }
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CateId = new SelectList(db.Categorys, "CateId", "Name", product.CateId);
            return View(product);
        }

    }
}

E-Farm/E-Farm/Controllers/ProductController.cs
using E_Farm.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace E_Farm.Controllers
{
    public class ProductController : Controller
    {
        DataEntities db = new DataEntities();

        // GET: Product
        public ActionResult Index(string search, int? pageNo)
        {
            var lstCategory = db.Categorys.ToList();
            Session["Category"] = lstCategory;

            if (search == null)
            {
                search = "";
            }
            int pageSize = 8;
            int pageNumber = pageNo ?? 1;
            try
            {
                return View(db.Products.Include(x => x.Category).Where(x => x.Price == float.Parse(search) && x.Status == true).ToList().ToPagedList(pageNumber, pageSize));
            }
            catch (Exception)
            {
                return View(db.Products.Include(x => x.Category).Where(x => x.Name.Contains(search) && x.Status == true).ToList().ToPagedList(pageNumber, pageSize));               
            }
        }

        public ActionResult OrderByPriceDESC()
        {

            return null;
        }
        
    }
}

E-Farm/E-Farm/Areas/Admin/Views/Products/Create.cshtml
@model E_Farm.Areas.Admin.Models.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align:center">Thêm mới sản phẩm</h2>

@using (Html.BeginForm("Create", "Products", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CateId, "CateId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CateId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CateId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceDiscount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceDiscount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceDiscount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="UploadImgProducts" id="UploadImgProducts" class="form-control" />
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Areas/Admin/Content/ckedit/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('Description');
    </script>
}

E-Farm/E-Farm/Areas/Admin/Views/Products/Details.cshtml
@model E_Farm.Areas.Admin.Models.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chi tiết sản phẩm</h2>

<div>
    <h4>Sản phẩm</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceDiscount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceDiscount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            <img src="@Model.Picture" width="200" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.Raw(Model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.ProductId }, new { @class = "btn btn-success" }) |
    @Html.ActionLink("Quay lại", "Index")
</p>

E-Farm/E-Farm/Areas/Admin/Views/Products/Edit.cshtml
@model E_Farm.Areas.Admin.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align:center">Chỉnh sửa sản phẩm</h2>

@using (Html.BeginForm("Edit", "Products", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductId)

        <div class="form-group">
            @Html.LabelFor(model => model.CateId, "CateId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CateId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CateId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceDiscount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceDiscount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceDiscount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                <input type="file" name="UploadImgProducts" id="UploadImgProducts" class="form-control" />
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.HiddenFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Areas/Admin/Content/ckedit/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('Description');
    </script>
}

E-Farm/E-Farm/Areas/Admin/Views/Products/Index.cshtml
@model PagedList.IPagedList<E_Farm.Areas.Admin.Models.Product>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align:center">Danh sách sản phẩm</h2>
<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>


@using (Html.BeginForm("Index", "Products", FormMethod.Get))
{
    <input type="text" id="search" name="search" />
    <button name="submit" type="submit" class="btn btn-primary">Tìm kiếm</button>
}

@Html.Raw(TempData["errMessage"])
<div id="result">
    <table class="table table-striped">
        <tr>
            <th>
                Danh mục
            </th>
            <th>
                Tên sản phẩm
            </th>
            <th>
                Số lượng
            </th>
            <th>
                Giá
            </th>
            <th>
                Giảm giá
            </th>
            <th>
                Ảnh
            </th>
            <th>
                Trạng thái
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PriceDiscount)
                </td>
                <td>
                    <img src="@item.Picture" width="300" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.ActionLink("Sửa", "Edit", new { id = item.ProductId }, new { @class = "btn btn-success" })
                    @Html.ActionLink("Chi tiết", "Details", new { id = item.ProductId }, new { @class = "btn btn-info" })
                    @Html.ActionLink("Xóa", "Delete", new { id = item.ProductId }, new { @class = "btn btn-danger", @onclick = "return confirm('Do you want delete this?')" })
                </td>
            </tr>
        }
    </table>
</div>
Page @(Model.PageCount < Model.PageNumber ? 1 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, pageNo => Url.Action("Index","Products", new { pageNo,search=Request.QueryString["search"] }))

E-Farm/E-Farm/Areas/Admin/Views/Products/Search.cshtml
@model IEnumerable<E_Farm.Areas.Admin.Models.Product>
@{
    ViewBag.Title = "Index";
    Layout = null;
}
<table class="table table-striped">
    <tr>
        <th>
            Danh mục
        </th>
        <th>
            Tên sản phẩm
        </th>
        <th>
            Số lượng
        </th>
        <th>
            Giá
        </th>
        <th>
            Giảm giá
        </th>
        <th>
            Ảnh
        </th>
        <th>
            Ngày tạo
        </th>
        <th>
            Trạng thái
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceDiscount)
            </td>
            <td>
                <img src="@item.Picture" width="300" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.ProductId }, new { @class = "btn btn-success" })
                @Html.ActionLink("Chi tiết", "Details", new { id = item.ProductId }, new { @class = "btn btn-info" })
                @Html.ActionLink("Xóa", "Delete", new { id = item.ProductId }, new { @class = "btn btn-danger", @onclick = "return confirm('Do you want delete this?')" })
            </td>
        </tr>
    }
</table>